---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: spotgun
  name: spotgun
  namespace: kube-system
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: spotgun
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - list
  - apiGroups:
      - ""
    resources:
      - nodes
    verbs:
      - get
      - update
  - apiGroups:
      - extensions
    resources:
      - replicasets
      - daemonsets
    verbs:
      - get
  - apiGroups:
      - ""
    resources:
      - pods/eviction
    verbs:
      - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: spotgun
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: spotgun
subjects:
- kind: ServiceAccount
  name: spotgun
  namespace: kube-system
---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: spotgun
  namespace: kube-system
  labels:
    app: spotgun
spec:
  template:
    metadata:
      name: spotgun
      labels:
        app: spotgun
    spec:
      serviceAccountName: spotgun
      containers:
      - name: spotgun
        image: 789035092620.dkr.ecr.us-east-1.amazonaws.com/spotgun
        env:
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
        resources:
          requests:
            cpu: 5m
            memory: 10Mi
          limits:
            cpu: 100m
            memory: 100Mi
        imagePullPolicy: Always
      nodeSelector:
        "node-role.kubernetes.io/spot-worker": "true"
